config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions
  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: %i[index]
  resources :quest_tags, param: :name, only: %i[show index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quest_tag.rb
class QuestTag < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :quest_tags, dependent: :destroy
  has_many :tags, through: :quest_tags

  validates :body, presence: true, length: { maximum: 255 }

  after_save_commit :create_hashtags

  private

  def create_hashtags
    self.tags =
      "#{body} #{answer}".downcase.
        scan(Tag::HASHTAG_REGEX).
        uniq.
        map { |tag| Tag.find_or_create_by(name: tag.delete('#'))}
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  HASHTAG_REGEX = /#[[:word:]-]+/

  has_many :quest_tags
  has_many :questions, through: :quest_tags

  def to_param
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  REG_NICKNAME = /\A[a-zA-Z0-9_]*\Z/
  REG_COLOR = /\A#[a-f0-9]{6}\z/i
  REG_EMAIL = /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_secure_password
  has_many :questions, dependent: :delete_all
  has_many :authored_questions, class_name: 'Question', foreign_key: 'author_id', dependent: :nullify

  after_validation :downcase_nickname
  validates :email, presence: true, uniqueness: true, format: { with: REG_EMAIL }
  validates :nav_color, format: { with: REG_COLOR }
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: REG_NICKNAME }

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  def to_param
    nickname
  end

  private

  def downcase_nickname
    nickname&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/quest_tags_controller.rb
class QuestTagsController < ApplicationController
  before_action :set_hashtag

  def show
    @questions = @tag.questions
  end

  def index
    @tags = Tag.all
  end

  private

  def set_hashtag
    @tag = Tag.find_by(name: params[:name])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[update destroy edit]

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)
    @question.author = current_user
    @user = User.find(question_params[:user_id])

    if @question.save
      redirect_to user_path(@question.user), notice: 'Новый вопрос создан!'
    else
      flash.now[:alert] = 'Поле вопроса пустое'
      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    @question.update(question_params)

    redirect_to user_path(@question.user), notice: 'Сохранили вопрос!'
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).last(10)
    @users = User.order(created_at: :desc).last(10)
    @tags = Tag.all
  end

  def new
    @user = User.find_by(nickname: params[:nickname])
    @question = Question.new(user: @user)
  end

  def edit
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save

      session[:user_id] = @user.id

      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation,
      :nav_color
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end

  def cap_color
    current_user&.nav_color || '#370617'
  end
end

app/helpers/quest_tags_helper.rb
module QuestTagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def author_present(author)
    if author == current_user && current_user.present?
      'От меня'
    elsif author.present?
      link_to "От #{ display_nickname(author) }", user_path(author)
    else
      'Анонимный вопрос'
    end
  end

  def render_with_hashtags(body)
    body.gsub(Tag::HASHTAG_REGEX) { |word| link_to word.downcase, "/quest_tags/#{word.downcase.delete('#')}" }.html_safe
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user&.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Askme</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="wrapper">
  <%= content_tag(:div, class: "navbar", style: "background-color: #{cap_color}") do %>
    <p class="title-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
    <div>
      <% if current_user.present? %>
        <%= link_to "#{display_nickname(current_user)}", user_path(current_user), class: 'mr-sm' %>
        <%= button_to 'Выйти', session_path, method: :delete %>
      <% else %>
        <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
        <%= link_to 'Вход', new_session_path, class: 'button button-yellow' %>
      <% end %>
    </div>
  <% end %>

  <% if flash[:notice].present? %>
    <p class="mb mt message message-notice"><%= flash[:notice] %></p>
  <% elsif flash[:alert].present? %>
    <p class="mb mt message message-alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/quest_tags/_tag.html.erb
<div class="mt-sm container">
  <p><%= link_to "##{tag.name}", quest_tag_path(tag) %></p>
</div>

app/views/quest_tags/index.html.erb
<div class="mt-sm container">
  <h2 class="title-lg">Все хэштеги</h2>
</div>

<div class="row buffer-bottom mt-md">
  <%= render partial: 'tag', collection: @tags %>
</div>

app/views/quest_tags/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mt-sm container">
  <h2 class="title-lg mb">
    Все вопросы с таким хэштегом:
    <%= @tag.name %>
  </h2>
  <%= link_to 'Хэштеги', quest_tags_path %>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для пользователя <%= link_to display_nickname(question.user), user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_with model: question, data: { turbo: false }  do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>
  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm pre-line">
  <%= render_with_hashtags(question.body) %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= render_with_hashtags(question.answer) %>
  </div>
<% end %>

<p class="mb-sm text-sm text-grey">
  <%= author_present(question.author) %>
</p>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>

      <%= link_to fa_icon(edit_icon), edit_question_path(question),
                  title: 'Изменить вопрос', class: 'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question),
                    method: :delete, title: 'Удалить вопрос', form: { data: { turbo_confirm: 'Точно удалить вопрос?' } } %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/hashtags.html.erb
<% @questions.each do |question| %>
  <div class="mt-sm container">
    <div class="mb-sm pre-line">
      <%= render_with_hashtags(question.body) %>
    </div>

    <% if question.answer.present? %>
      <div class="mb-sm text-dark-red">
        <%= render_with_hashtags(question.answer) %>
      </div>
    <% end %>

    <p class="mb-sm text-sm text-grey">
      <%= author_present(question.author) %>
    </p>

    <div class="text-sm question-footer">
      <div class="text-grey">
        <%= l(question.created_at, format: :short) %>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: { user: user } %>
    <% end %>
  </div>
</div>

<% if @tags.any? %>
  <div class='container mt-sm'>
    <% @tags.each do |hashtag| %>
      <%= link_to "##{hashtag.name}", quest_tag_path(hashtag) %>
    <% end %>
  </div>
<% end %>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для пользователя <%= link_to display_nickname(question.user), user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>

  <p class="mb">для <%= link_to display_nickname(@user), user_path(@user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>

  <p class="mt-sm">
    <%= link_to "Все вопросы #{display_nickname(@question.user)}", user_path(@question.user) %>
  </p>
</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>
</div>

app/views/questions/show_hashtags.html.erb
<% @questions.each do |question| %>
  <div class="mt-sm container">
    <div class="mb-sm pre-line">
      <%= render_with_hashtags(question.body) %>
    </div>

    <% if question.answer.present? %>
      <div class="mb-sm text-dark-red">
        <%= render_with_hashtags(question.answer) %>
      </div>
    <% end %>

    <p class="mb-sm text-sm text-grey">
      <%= author_present(question.author) %>
    </p>

    <div class="text-sm question-footer">
      <div class="text-grey">
        <%= l(question.created_at, format: :short) %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_no_questions.html.erb
<div class="container text-center">
  <p class="title-sm text-grey">
    У этого пользователя пока никто ничего не спросил
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  <%= link_to "Дай, спрошу!", new_question_path(nickname: user),
              class: 'button button-main' %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: display_nickname(user), class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование пользователя</h2>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: display_nickname(@user), class: 'rounded' %></p>
    <p class="text-sm">Чтобы добавить или поменять аватар - зарегистрируйтесь
      на <%= link_to 'Gravatar', 'https://gravatar.com' %> и загрузите фото</p>
  </div>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nav_color, 'Цвет шапки сайта' %></p>
      <p><%= form.color_field :nav_color %></p>

      <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user),
                  method: :delete,
                  form: { data: { turbo_confirm: "Вы точно хотите удалить свой профиль?" } },
                  class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: { user: @user } %>
  </div>

  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>

  <p class="text-bold mt mb-lg"><%= display_nickname(@user) %></p>
</div>

<% if @questions.any? %>
  <div class="container">
    <%= link_to "Спроси меня", new_question_path(nickname: @user.nickname),
                class: 'button button-yellow' %>
  </div>

  <div class="container mt-sm">
    <h2 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>
  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <%= render question %>
    </div>
  <% end %>
<% else %>
  <%= render partial: 'no_questions', locals: { user: @user } %>
<% end %>